name: Deploy to Google Apps Script

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run pre-deployment checks
      run: npm run predeploy
    
    - name: Build project
      run: npm run build
    
    - name: Setup clasp
      run: |
        npm install -g @google/clasp
        echo "${{ secrets.CLASP_CREDENTIALS }}" > ~/.clasprc.json
    
    - name: Deploy to Google Apps Script
      run: |
        cd dist
        clasp push --force
        clasp version "GitHub Actions Deployment - ${{ github.ref_name }}"
        clasp deploy --description "Automated deployment from GitHub Actions - ${{ github.ref_name }}"
    
    - name: Create GitHub Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref_name }}
        release_name: Release ${{ github.ref_name }}
        body: |
          Automated release from GitHub Actions
          
          ## Changes
          - See commit history for changes
          
          ## Bundle Info
          - Built with Node.js 20.x
          - Deployed to Google Apps Script
        draft: false
        prerelease: false